# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created, released]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Check tag name matches setup.py version
      run: |
       ver=`python setup.py --version`
       tag="refs/tags/$ver"
       if [[ "$tag" != $GITHUB_REF ]] 
          then echo Tag $GITHUB_REF does not match $ver from setup.py >&2
          echo Please update rocrate/_version.py
          false
       fi
    - name: Test
      run: |
        python setup.py test
    - name: Build and publish
      if: "${{ github.event.action == 'released' }}"
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel        
        twine upload dist/*
